---
title: "binomial tests off website"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(foreach)
library(viridis)

control_props = read_csv("./data/control_props.csv")
input_genes = read_csv("./data/study_genes.csv")
wells = read_csv("./data/wells.csv")
chem_list = wells %>% ungroup() %>%  distinct(group) %>% pull(group)
subs = read_csv("./data/subs_gene_body.csv")
all_gene_length = read_csv("./data/all_gene_length.csv")
grch37_gene_names = read_csv("./data/grch37_gene_names.csv")


gene_list_names = colnames(input_genes)
#####################
####################
###### setup loop for binomial tests
#####################
######################
# This loop gives us the total mutations for each chemical/disease gene list combo. This number will be the numerator in the binomial tests.
# We also get the denominator for binomial tests, which the the number of "gene_wells", or the number of genes in the list times the 
# the number of wells that were treated with that chemical. The denominator represents how many opportunists each chemical had to mutate these genes. 
input_list = foreach(name = gene_list_names, .combine = "rbind") %do% {
        gene_list_x = input_genes %>% dplyr::select(name) %>% dplyr::rename(gene=name) %>% filter(!is.na(gene))
        total_nucleotides = gene_list_x %>% left_join(all_gene_length) %>% summarize(mean1 = mean(Length, na.rm=TRUE)) %>% pull(mean1)
        chem_list_df = data.frame(chem_list)
        
        input_mutations = foreach(chemical = chem_list, .combine = "rbind") %do% {
            gene_number = gene_list_x %>% filter(gene %in% grch37_gene_names$gene_name)
            data1 = gene_list_x  %>% 
                    left_join(subs) %>%    
                    filter(group == chemical) %>% 
                    group_by(group,chem,dose,replicate) %>% 
                    summarize(n=n()) %>% 
                          full_join(wells) %>% 
                          filter(group == chemical) %>% 
                    mutate(n = replace_na(n, 0)) %>% 
                    ungroup() %>% 
                    summarize(total_mutations = sum(n),
                            genes = length(gene_number$gene),
                            wells = length(n)) %>% 
                    mutate(gene_wells = genes*wells) %>% 
                    mutate(gene_wells_nucleotides = gene_wells*total_nucleotides)
  
            return(data1)
            }
    input_mutations = input_mutations %>% bind_cols(chem_list_df) %>% 
        mutate(name = name) 
}

# Renaming
input = input_list %>% 
  dplyr::rename(input_mutations = total_mutations,input_genewells = gene_wells, chemical = chem_list) %>%
  filter(chemical != "Control")%>% 
  dplyr::select(chemical, input_mutations, input_genewells, name, genes, wells)

# Add in control mutation rates
bin_test_data = input %>% left_join(control_props)

##################
###################
#Binomial test loop
###################
#################
input_binomial_tests = foreach (list_name = gene_list_names, .combine = "rbind") %do%
  {
    gene_list_x = bin_test_data %>% filter(name == list_name)
    
input_tests=foreach (row = 1:nrow(gene_list_x), .combine = "rbind") %do% {
  # First number is numerator, second number is denominator, third number is expected mutation rate
  test1 = binom.test(gene_list_x[["input_mutations"]][[row]],
                     gene_list_x[["input_genewells"]][[row]],
                     gene_list_x[["mean"]][[row]],
                     alternative = "two.sided")
  broom::tidy(test1) %>% mutate(chemical = gene_list_x[["chemical"]][[row]])
  
}
#happens between the rbinds
input_tests = input_tests %>% mutate(name = list_name)
  }

# Add back bin_test_data to add back the control rate (mean) and calucalte differences and fold changes
input_binomial_tests_final = input_binomial_tests %>% 
  mutate(treatment = "Treated") %>% 
  left_join(bin_test_data) %>% 
  mutate(difference = estimate - mean,
         fold_change = estimate/mean)

tables3_data_gene_body = input_binomial_tests_final %>%
  dplyr::select(chemical, name, input_mutations, genes, wells, estimate, conf.low, conf.high, p.value, fold_change, difference)
#write_csv(tables3_data_gene_body, "tables3_data_gene_body.csv")

input_binomial_tests_final$chemical <- factor(input_binomial_tests_final$chemical,levels = c("Radiation", "PAH", "Alkylating Agent", "Nitro-PAH", "ROS/NOS", "Heterocyclic Amine", "Drug Therapy", "DNA Damage Response Inhibitors", "Aromatic Amine", "Metal", "Nitrosamine", "Aldehydes", "Other"))


```

Plotting
```{r}
final_data = input_binomial_tests_final

final_data_heatmap = final_data %>%  filter(treatment == "Treated") %>% 
  mutate(adj_p = p.adjust(p.value, method = "bonferroni")) %>%
  mutate(significance = ifelse(p.value > 0.05, NA, "*"))%>%
  mutate(significance = ifelse(adj_p > 0.05, significance, "**"))%>% 
  mutate(significance = ifelse(significance =="*" & difference<0, "†",significance))%>% 
  mutate(significance = ifelse(significance =="**" & difference<0, "††",significance))%>%
  mutate(color = ifelse(difference>0 & !is.na(significance),"darkturquoise", NA ))%>% 
  mutate(color = ifelse(difference<0 & !is.na(significance),"red", color))%>% 
  mutate(color = ifelse(is.na(significance),"black", color))


bbtheme <- theme(axis.text.x = element_text(size=15,face = "bold"),
                 axis.text.y = element_text(size=15, face = "bold"),
                 axis.title.x = element_text(size=20, face = "bold"),
                 axis.title.y = element_text(size=20, face = "bold"),
                 plot.title = element_text(size=20, face = "bold"))


final_data_heatmap$name <- factor(final_data_heatmap$name,
                                  levels = c("autism", "adhd", "schizophrenia", "obesity", "type 2 diabetes", "alzheimers", "CHD", "orofacial cleft","coronary artery", "als"),
                                  labels = c("Autism", "ADHD", "Schizophrenia", "Obesity", "Type 2 Diabetes", "Alzheimer's", "Congenital Heart Disease", "Oral Cleft","Coronary Artery", "ALS")
                                  )


heatmap1 = ggplot(final_data_heatmap, aes(x = name, y = chemical, fill = difference)) + 
  geom_tile()+
  geom_text(aes(label = significance,color = color), fontface = "bold", size = 6) +
  scale_color_identity() +
  scale_fill_viridis(option = "B")+
  labs(
      title = "Gene Body Mutations\n(Observed - Expected)",
      fill = "Observed\nminus expected\nmutation rate",
       y = "",
       x = "")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  bbtheme
heatmap1
```


Human lung tumor
```{r}

human_recurring = read_csv("./data/humanwgs_recurring.csv") %>% mutate(gene = as.character(gene))
human_wgs_mutated = read_csv("./data/humanwgs_mutated_genes.csv") %>% mutate(gene = as.character(gene)) %>% left_join(human_recurring) %>% mutate(number = replace_na(number,1)) %>% dplyr::rename(n = number)

control_props = read_csv("./data/control_props_humanwgs_tumor.csv")

subs = read_csv("./data/subs_gene_body.csv")
hline_data = control_props %>% dplyr::select(mean) %>% dplyr::rename(hline = mean)
all_gene_length = read_csv("./data/all_gene_length.csv")
input_genes = read_csv("./data/study_genes.csv")

#loop
#input_genes=input_genes %>% dplyr::select(CHD) %>% #dplyr::rename(gene=CHD)

gene_list_names = colnames(input_genes)
#####################
####################
###### setup loop for binomial tests
#####################
######################
input_list = foreach(name = gene_list_names, .combine = "rbind") %do% {
  gene_list_x = input_genes %>% dplyr::select(name) %>% dplyr::rename(gene=name) %>% filter(!is.na(gene))
  
  gene_number = gene_list_x %>% filter(gene %in% grch37_gene_names$gene_name)
  
  data1 = gene_list_x  %>% 
        left_join(human_wgs_mutated)%>% 
        mutate(n = replace_na(n, 0)) %>% 
    summarize(total_mutations = sum(n),
                  genes = length(gene_number$gene)) %>% 
    mutate(wells = 14,
           name = name)%>% 
    mutate(gene_wells = genes*wells)
    
}



#chem_list_df = data.frame(chem_list)
#input_mutations$chemical = chem_list_df$chem_list

input = input_list %>% 
  dplyr::rename(input_mutations = total_mutations,input_genewells = gene_wells) %>% 
  dplyr::select(input_mutations, input_genewells, name)


###for this data, mean is the hypothesized proportion, input mutations is the numebrator, and input gene wells is the number of genes in each list times 14 (because there are 14 tumor samples)
bin_test_data = input %>% mutate(mean = control_props$mean)

##################
###################
#Binomial test loop
###################
#################
input_binomial_tests = foreach (list_name = gene_list_names, .combine = "rbind") %do%
  {
    gene_list_x = bin_test_data %>% filter(name == list_name)
test1 = binom.test(gene_list_x[["input_mutations"]],gene_list_x[["input_genewells"]],gene_list_x[["mean"]], alternative = "two.sided")
  broom::tidy(test1) %>% mutate(name = list_name)
}



############
###############
##### add control 
###############
##############
############hlines for expected mutations for random gene sets
tumor_hline = control_props %>% pull(mean)
input_binomial_tests_final = input_binomial_tests%>% 
  mutate(name = ifelse(name == "orofacial cleft", "oral cleft", name))

input_binomial_tests_final = input_binomial_tests_final %>% mutate(fold_change = estimate/tumor_hline,
                                                                   difference = estimate - tumor_hline)


final_data_tumor_heatmap = input_binomial_tests_final %>% 
  mutate(adj_p = p.adjust(p.value, method = "bonferroni")) %>%
  mutate(significance = ifelse(p.value > 0.05, NA, "*"))%>%
  mutate(significance = ifelse(adj_p > 0.05, significance, "**"))%>% 
  mutate(significance = ifelse(significance =="*" & difference<0, "†",significance))%>% 
  mutate(significance = ifelse(significance =="**" & difference<0, "††",significance))%>%
  mutate(color = ifelse(difference>0 & !is.na(significance),"darkturquoise", NA ))%>% 
  mutate(color = ifelse(difference<0 & !is.na(significance),"red", color))%>% 
  mutate(color = ifelse(is.na(significance),"black", color))%>% 
  mutate(chemical = "Air Pollution\nAssociated Lung Tumor")


final_data_tumor_heatmap$name <- factor(final_data_tumor_heatmap$name,
                                  levels = c("autism", "adhd", "schizophrenia", "obesity", "type 2 diabetes", "alzheimers", "CHD", "oral cleft","coronary artery", "als"),
                                  labels = c("Autism", "ADHD", "Schizophrenia", "Obesity", "Type 2 Diabetes", "Alzheimer's", "Congenital Heart Disease", "Oral Cleft","Coronary Artery", "ALS")
                                  )


heatmap_tumor = ggplot(final_data_tumor_heatmap, aes(x = name,y = chemical, fill = difference)) + 
  geom_tile()+
  geom_text(aes(label = significance), color = "darkturquoise", fontface = "bold", size = 6) +
  scale_fill_viridis(option = "B")+
  labs(fill = "Observed\nminus expected\nmutation rate",
       y = "",
       x = "")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  bbtheme
heatmap_tumor
```

CDS
```{r}
control_props = read_csv("./data/control_props_cds.csv")
input_genes = read_csv("./data/study_genes.csv")
wells = read_csv("./data/wells.csv")
chem_list = wells %>% ungroup() %>%  distinct(group) %>% pull(group)
subs = read_csv("./data/subs_cds.csv")
hline_data = read_csv("./data/hline_data_cds.csv")
all_gene_length = read_csv("./data/all_gene_length_coding.csv")
gene_list_names = colnames(input_genes)
#####################
####################
###### setup loop for binomial tests
#####################
######################
input_list = foreach(name = gene_list_names, .combine = "rbind") %do% {
  gene_list_x = input_genes %>% dplyr::select(name) %>% dplyr::rename(gene=name) %>% filter(!is.na(gene))
  
  #ultimately not doing a per nucleotide analysis. The control is randomly sampled cds
  total_nucleotides_per_gene = all_gene_length %>% group_by(gene) %>% summarise(Length = sum(Length))  
  total_nucleotides = gene_list_x %>% left_join(total_nucleotides_per_gene) %>% summarize(mean1 = mean(Length, na.rm=TRUE)) %>% pull(mean1)

chem_list_df = data.frame(chem_list)
input_mutations = foreach(chemical = chem_list, .combine = "rbind") %do% {
  gene_number = gene_list_x %>% filter(gene %in% grch37_gene_names$gene_name)
  data1 = gene_list_x  %>% 
        left_join(subs) %>%    
        filter(group == chemical) %>% 
        group_by(group,chem,dose,replicate) %>% 
        summarize(n=n()) %>% 
        full_join(wells) %>% 
        filter(group == chemical) %>% 
        mutate(n = replace_na(n, 0)) %>% 
        ungroup() %>% 
        summarize(total_mutations = sum(n),
                  genes = length(gene_number$gene),
                  wells = length(n)) %>% 
    mutate(gene_wells = genes*wells) %>% 
    mutate(gene_wells_nucleotides = gene_wells*total_nucleotides)
  
  return(data1)}
input_mutations = input_mutations %>% bind_cols(chem_list_df) %>% 
  mutate(name = name) 
}

input = input_list %>% 
  dplyr::rename(input_mutations = total_mutations,input_genewells = gene_wells, chemical = chem_list) %>% 
  filter(chemical != "Control") %>% 
  dplyr::select(chemical, input_mutations, input_genewells, name, genes, wells)

bin_test_data = input %>% left_join(control_props)

##################
###################
#Binomial test loop
###################
#################
input_binomial_tests = foreach (list_name = gene_list_names, .combine = "rbind") %do%
  {
    gene_list_x = bin_test_data %>% filter(name == list_name)
    
input_tests=foreach (row = 1:nrow(gene_list_x), .combine = "rbind") %do% {
  
  test1 = binom.test(gene_list_x[["input_mutations"]][[row]],
                     gene_list_x[["input_genewells"]][[row]],
                     gene_list_x[["mean"]][[row]],
                     alternative = "two.sided")
  broom::tidy(test1) %>% mutate(chemical = gene_list_x[["chemical"]][[row]])
  
}
#happens between the rbinds
input_tests = input_tests %>% mutate(name = list_name)
  }

input_binomial_tests_final = input_binomial_tests %>% 
  mutate(treatment = "Treated") %>% 
  left_join(bin_test_data) %>% 
  mutate(difference = estimate - mean,
         fold_change = estimate/mean)


tables3_data_cds = input_binomial_tests_final %>%
  dplyr::select(chemical, name, input_mutations, genes, wells, estimate, conf.low, conf.high, p.value, fold_change, difference)
#write_csv(tables3_data_cds, "tables3_data_cds.csv")

# Order to match the others
input_binomial_tests_final$chemical <- factor(input_binomial_tests_final$chemical,levels = c("Radiation", "PAH", "Alkylating Agent", "Nitro-PAH", "ROS/NOS", "Heterocyclic Amine", "Drug Therapy", "DNA Damage Response Inhibitors", "Aromatic Amine", "Metal", "Nitrosamine", "Aldehydes", "Other"))


final_data_heatmap = input_binomial_tests_final %>% 
  mutate(adj_p = p.adjust(p.value, method = "bonferroni")) %>%
  mutate(significance = ifelse(p.value > 0.05, NA, "*"))%>%
  mutate(significance = ifelse(adj_p > 0.05, significance, "**"))%>% 
  mutate(significance = ifelse(significance =="*" & difference<0, "†",significance))%>% 
  mutate(significance = ifelse(significance =="**" & difference<0, "††",significance))%>%
  mutate(color = ifelse(difference>0 & !is.na(significance),"darkturquoise", NA ))%>% 
  mutate(color = ifelse(difference<0 & !is.na(significance),"red", color))%>% 
  mutate(color = ifelse(is.na(significance),"black", color))


# Order to match the others
final_data_heatmap$name <- factor(final_data_heatmap$name,
                                  levels = c("autism", "adhd", "schizophrenia", "obesity", "type 2 diabetes", "alzheimers", "CHD", "orofacial cleft","coronary artery", "als"),
                                  labels = c("Autism", "ADHD", "Schizophrenia", "Obesity", "Type 2 Diabetes", "Alzheimer's", "Congenital Heart Disease", "Oral Cleft","Coronary Artery", "ALS")
                                  )


bbtheme <- theme(axis.text.x = element_text(size=15,face = "bold"),
                 axis.text.y = element_text(size=15, face = "bold"),
                 axis.title.x = element_text(size=20, face = "bold"),
                 axis.title.y = element_text(size=20, face = "bold"),
                 plot.title = element_text(size=20, face = "bold"))



##need to run code in human_wgs_tumor.rmd
heatmap_cds = ggplot(final_data_heatmap, aes(x = name, y = chemical, fill = difference)) + 
  geom_tile()+
  geom_text(aes(label = significance), color = "darkturquoise", fontface = "bold", size = 6) +
  scale_fill_viridis(option = "B")+
  labs(
    title = "Coding Sequence Mutations\n(Observed - Expected)",
    fill = "Observed\nminus expected\nmutation rate",
       y = "",
       x = "")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  bbtheme

heatmap_cds

```


```{r}
library(ggpubr)
library(patchwork)
s <- plot_spacer()
heatmap2 = heatmap1+ theme(axis.text.x = element_blank())
#heatmap_tumor = heatmap_tumor+ theme(axis.title.y = element_blank())

heatmap_cds2 =heatmap_cds + theme(axis.text.y = element_blank())

p1 = ggarrange(ggarrange(heatmap2+theme(legend.title= element_blank()), heatmap_tumor+theme(legend.title= element_blank()), labels = c("", "C"), align = "v", nrow = 2, ncol = 1, heights = c(5,3)),
        ggarrange(heatmap_cds2+theme(legend.title= element_blank()),s+ theme_bw()+theme(panel.border = element_rect(color = "white")), align = "v", nrow = 2, ncol = 1, heights = c(7,1)),
      ncol = 2,
      nrow = 1,
      labels = c("A","B"),
      widths = c(5,3.5)
      ) 


p1

#ggsave("heatmap3_3_23.tiff",p1,dpi = 300)
#ggsave("heatmap3_3_23.emf",p1,dpi = 300)
#ggsave("heatmap3_3_23.jpg",p1,dpi = 300)

```

